In [2]:
import numpy as np

In [3]:
# array creation
scl = np.array([[101,102,103,104],[1321,2432,3543,4654],[67,98,87,35]])
scl

array([[ 101,  102,  103,  104],
       [1321, 2432, 3543, 4654],
       [  67,   98,   87,   35]])

In [4]:
# explortion

scl.shape
scl.ndim
scl.size

12

In [5]:
# transform data to readable in diff form
scl.T

array([[ 101, 1321,   67],
       [ 102, 2432,   98],
       [ 103, 3543,   87],
       [ 104, 4654,   35]])

In [8]:
# add a new data
newcol = np.array([[109],[9879],[58]])
scl = np.hstack((scl,newcol))
scl

array([[ 101,  102,  103,  104,  109,  109],
       [1321, 2432, 3543, 4654, 9879, 9879],
       [  99,   98,   87,   67,   58,   58]])

In [9]:
# modification
student = scl[0]
subject = scl[1]
marks = scl[2]

marks[0]=99
marks[3]=67.45

np.delete(subject,5)

subject

marks

array([99, 98, 87, 67, 58, 58])

In [10]:
data = np.array([student,subject,marks])
data

array([[ 101,  102,  103,  104,  109,  109],
       [1321, 2432, 3543, 4654, 9879, 9879],
       [  99,   98,   87,   67,   58,   58]])

In [11]:
# copy
nscl=scl.copy()
nscl[0][5]=108
nscl
'''array([[ 101,  102,  103,  104,  107,  108,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''

scl


array([[ 101,  102,  103,  104,  109,  109],
       [1321, 2432, 3543, 4654, 9879, 9879],
       [  99,   98,   87,   67,   58,   58]])

In [12]:
# view

vscl = scl.view()
vscl[1][4]=8978
vscl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl
'''array([[ 101,  102,  103,  104,  107,  107,  109],
       [1321, 2432, 3543, 4654, 8978, 7897, 9879],
       [  99,   98,   87,   67,   76,   76,   58]])'''
scl

array([[ 101,  102,  103,  104,  109,  109],
       [1321, 2432, 3543, 4654, 8978, 9879],
       [  99,   98,   87,   67,   58,   58]])